const ghXml = (encodedCode: string) => `<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Archive name="Root">
  <!--Grasshopper archive-->
  <!--Grasshopper and GH_IO.dll are copyrighted by Robert McNeel & Associates-->
  <!--Archive generated by GH_IO.dll file utility library {0.2.0002}-->
  <items count="1">
    <item name="ArchiveVersion" type_name="gh_version" type_code="80">
      <Major>0</Major>
      <Minor>2</Minor>
      <Revision>2</Revision>
    </item>
  </items>
  <chunks count="1">
    <chunk name="Clipboard">
      <items count="1">
        <item name="plugin_version" type_name="gh_version" type_code="80">
          <Major>1</Major>
          <Minor>0</Minor>
          <Revision>8</Revision>
        </item>
      </items>
      <chunks count="5">
        <chunk name="DocumentHeader">
          <items count="5">
            <item name="DocumentID" type_name="gh_guid" type_code="9">c5ffc9b0-b359-43ea-908c-d1876d580060</item>
            <item name="Preview" type_name="gh_string" type_code="10">Shaded</item>
            <item name="PreviewMeshType" type_name="gh_int32" type_code="3">1</item>
            <item name="PreviewNormal" type_name="gh_drawing_color" type_code="36">
              <ARGB>255;255;38;0</ARGB>
            </item>
            <item name="PreviewSelected" type_name="gh_drawing_color" type_code="36">
              <ARGB>100;0;150;0</ARGB>
            </item>
          </items>
        </chunk>
        <chunk name="DefinitionProperties">
          <items count="4">
            <item name="Date" type_name="gh_date" type_code="8">639070156451363430</item>
            <item name="Description" type_name="gh_string" type_code="10"></item>
            <item name="KeepOpen" type_name="gh_bool" type_code="1">false</item>
            <item name="Name" type_name="gh_string" type_code="10"></item>
          </items>
          <chunks count="3">
            <chunk name="Revisions">
              <items count="1">
                <item name="RevisionCount" type_name="gh_int32" type_code="3">0</item>
              </items>
            </chunk>
            <chunk name="Projection">
              <items count="2">
                <item name="Target" type_name="gh_drawing_point" type_code="30">
                  <X>10</X>
                  <Y>10</Y>
                </item>
                <item name="Zoom" type_name="gh_single" type_code="5">1</item>
              </items>
            </chunk>
            <chunk name="Views">
              <items count="1">
                <item name="ViewCount" type_name="gh_int32" type_code="3">0</item>
              </items>
            </chunk>
          </chunks>
        </chunk>
        <chunk name="RcpLayout">
          <items count="1">
            <item name="GroupCount" type_name="gh_int32" type_code="3">0</item>
          </items>
        </chunk>
        <chunk name="GHALibraries">
          <items count="1">
            <item name="Count" type_name="gh_int32" type_code="3">1</item>
          </items>
          <chunks count="1">
            <chunk name="Library" index="0">
              <items count="4">
                <item name="Author" type_name="gh_string" type_code="10">Robert McNeel &amp; Associates</item>
                <item name="Id" type_name="gh_guid" type_code="9">00000000-0000-0000-0000-000000000000</item>
                <item name="Name" type_name="gh_string" type_code="10">Grasshopper</item>
                <item name="Version" type_name="gh_string" type_code="10">8.27.26019.16022</item>
              </items>
            </chunk>
          </chunks>
        </chunk>
        <chunk name="DefinitionObjects">
          <items count="1">
            <item name="ObjectCount" type_name="gh_int32" type_code="3">1</item>
          </items>
          <chunks count="1">
            <chunk name="Object" index="0">
              <items count="2">
                <item name="GUID" type_name="gh_guid" type_code="9">b6ba1144-02d6-4a2d-b53c-ec62e290eeb7</item>
                <item name="Name" type_name="gh_string" type_code="10">C# Script</item>
              </items>
              <chunks count="1">
                <chunk name="Container">
                  <items count="14">
                    <item name="Description" type_name="gh_string" type_code="10">C# scripting component</item>
                    <item name="GraftStandardOutputLines" type_name="gh_bool" type_code="1">true</item>
                    <item name="InstanceGuid" type_name="gh_guid" type_code="9">69806cb7-8b81-4a23-b422-69105eec5fb1</item>
                    <item name="MarshGuids" type_name="gh_bool" type_code="1">false</item>
                    <item name="MarshInputs" type_name="gh_bool" type_code="1">false</item>
                    <item name="MarshOutputs" type_name="gh_bool" type_code="1">false</item>
                    <item name="Name" type_name="gh_string" type_code="10">C# Script</item>
                    <item name="NickName" type_name="gh_string" type_code="10">C#</item>
                    <item name="ScriptComponentVersion" type_name="gh_int32" type_code="3">3</item>
                    <item name="Tooltip" type_name="gh_string" type_code="10"></item>
                    <item name="UsingLibraryInputParam" type_name="gh_bool" type_code="1">false</item>
                    <item name="UsingScriptInputParam" type_name="gh_bool" type_code="1">false</item>
                    <item name="UsingScriptOutputParam" type_name="gh_bool" type_code="1">false</item>
                    <item name="UsingStandardOutputParam" type_name="gh_bool" type_code="1">true</item>
                  </items>
                  <chunks count="4">
                    <chunk name="Attributes">
                      <items count="3">
                        <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                          <X>469</X>
                          <Y>124</Y>
                          <W>64</W>
                          <H>44</H>
                        </item>
                        <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                          <X>495</X>
                          <Y>146</Y>
                        </item>
                        <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                      </items>
                    </chunk>
                    <chunk name="ParameterData">
                      <items count="6">
                        <item name="InputCount" type_name="gh_int32" type_code="3">2</item>
                        <item name="InputId" index="0" type_name="gh_guid" type_code="9">08908df5-fa14-4982-9ab2-1aa0927566aa</item>
                        <item name="InputId" index="1" type_name="gh_guid" type_code="9">08908df5-fa14-4982-9ab2-1aa0927566aa</item>
                        <item name="OutputCount" type_name="gh_int32" type_code="3">2</item>
                        <item name="OutputId" index="0" type_name="gh_guid" type_code="9">3ede854e-c753-40eb-84cb-b48008f14fd4</item>
                        <item name="OutputId" index="1" type_name="gh_guid" type_code="9">08908df5-fa14-4982-9ab2-1aa0927566aa</item>
                      </items>
                      <chunks count="4">
                        <chunk name="InputParam" index="0">
                          <items count="12">
                            <item name="AllowTreeAccess" type_name="gh_bool" type_code="1">true</item>
                            <item name="Description" type_name="gh_string" type_code="10">No conversion</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">6d73acde-9176-4791-a8ed-96e2c666dd00</item>
                            <item name="Name" type_name="gh_string" type_code="10">x</item>
                            <item name="NickName" type_name="gh_string" type_code="10">x</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">true</item>
                            <item name="ScriptParamAccess" type_name="gh_int32" type_code="3">0</item>
                            <item name="ScriptParameterVersion" type_name="gh_int32" type_code="3">2</item>
                            <item name="ShowTypeHints" type_name="gh_bool" type_code="1">true</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="ToolTip" type_name="gh_string" type_code="10"></item>
                            <item name="TypeHintID" type_name="gh_guid" type_code="9">6a184b65-baa3-42d1-a548-3915b401de53</item>
                          </items>
                          <chunks count="2">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>471</X>
                                  <Y>126</Y>
                                  <W>9</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>477</X>
                                  <Y>136</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                            <chunk name="ConverterData">
                              <items count="2">
                                <item name="AssemblyName" type_name="gh_string" type_code="10">System.Private.CoreLib</item>
                                <item name="TypeName" type_name="gh_string" type_code="10">System.Object</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="InputParam" index="1">
                          <items count="12">
                            <item name="AllowTreeAccess" type_name="gh_bool" type_code="1">true</item>
                            <item name="Description" type_name="gh_string" type_code="10">No conversion</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">b20d6bef-d740-4876-849a-43990b28d41c</item>
                            <item name="Name" type_name="gh_string" type_code="10">y</item>
                            <item name="NickName" type_name="gh_string" type_code="10">y</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">true</item>
                            <item name="ScriptParamAccess" type_name="gh_int32" type_code="3">0</item>
                            <item name="ScriptParameterVersion" type_name="gh_int32" type_code="3">2</item>
                            <item name="ShowTypeHints" type_name="gh_bool" type_code="1">true</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="ToolTip" type_name="gh_string" type_code="10"></item>
                            <item name="TypeHintID" type_name="gh_guid" type_code="9">6a184b65-baa3-42d1-a548-3915b401de53</item>
                          </items>
                          <chunks count="2">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>471</X>
                                  <Y>146</Y>
                                  <W>9</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>477</X>
                                  <Y>156</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                            <chunk name="ConverterData">
                              <items count="2">
                                <item name="AssemblyName" type_name="gh_string" type_code="10">System.Private.CoreLib</item>
                                <item name="TypeName" type_name="gh_string" type_code="10">System.Object</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="OutputParam" index="0">
                          <items count="6">
                            <item name="Description" type_name="gh_string" type_code="10">Standard output and error contents collected during script run</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">11b03cfd-17f3-4ea6-8621-b53c014e8cde</item>
                            <item name="Name" type_name="gh_string" type_code="10">out</item>
                            <item name="NickName" type_name="gh_string" type_code="10">out</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>510</X>
                                  <Y>126</Y>
                                  <W>21</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>520.5</X>
                                  <Y>136</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="OutputParam" index="1">
                          <items count="12">
                            <item name="AllowTreeAccess" type_name="gh_bool" type_code="1">false</item>
                            <item name="Description" type_name="gh_string" type_code="10">No conversion</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">2e6e4c9c-83cc-46c0-a4a8-a475e3e87151</item>
                            <item name="Name" type_name="gh_string" type_code="10">a</item>
                            <item name="NickName" type_name="gh_string" type_code="10">a</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                            <item name="ScriptParamAccess" type_name="gh_int32" type_code="3">0</item>
                            <item name="ScriptParameterVersion" type_name="gh_int32" type_code="3">2</item>
                            <item name="ShowTypeHints" type_name="gh_bool" type_code="1">true</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="ToolTip" type_name="gh_string" type_code="10"></item>
                            <item name="TypeHintID" type_name="gh_guid" type_code="9">6a184b65-baa3-42d1-a548-3915b401de53</item>
                          </items>
                          <chunks count="2">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>510</X>
                                  <Y>146</Y>
                                  <W>21</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>520.5</X>
                                  <Y>156</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                            <chunk name="ConverterData">
                              <items count="2">
                                <item name="AssemblyName" type_name="gh_string" type_code="10">System.Private.CoreLib</item>
                                <item name="TypeName" type_name="gh_string" type_code="10">System.Object</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                      </chunks>
                    </chunk>
                    <chunk name="Script">
                      <items count="5">
                        <item name="MarshGuids" type_name="gh_bool" type_code="1">false</item>
                        <item name="MarshInputs" type_name="gh_bool" type_code="1">false</item>
                        <item name="MarshOutputs" type_name="gh_bool" type_code="1">false</item>
                        <item name="Text" type_name="gh_string" type_code="10">${encodedCode}</item>
                        <item name="Title" type_name="gh_string" type_code="10">C#</item>
                      </items>
                      <chunks count="1">
                        <chunk name="LanguageSpec">
                          <items count="2">
                            <item name="Taxon" type_name="gh_string" type_code="10">*.*.csharp</item>
                            <item name="Version" type_name="gh_string" type_code="10">*.*</item>
                          </items>
                        </chunk>
                      </chunks>
                    </chunk>
                    <chunk name="ScriptEditor">
                      <items count="1">
                        <item name="StartBounds" type_name="gh_drawing_rectangle" type_code="34">
                          <X>588</X>
                          <Y>199</Y>
                          <W>550</W>
                          <H>650</H>
                        </item>
                      </items>
                    </chunk>
                  </chunks>
                </chunk>
              </chunks>
            </chunk>
          </chunks>
        </chunk>
      </chunks>
    </chunk>
  </chunks>
</Archive>`
